### ISSUE TITLE
Version(s) of macOS you tried on?

### ISSUE THREAD

**Issue by solzard** [ulwlu/dotfiles#13]
Which version(s) of macOS did you do the whole research and verified options of `macos.sh`?
I'm going to upgrade from Mojave (`ver 10.14.6`) to Big Sur. 
Some options I tried to `default read ~` on my MBP don't exist, no so many though.

**Comment by ulwlu** [comment]
Hi. I searched them on Catalina, as code stated it here.

https://github.com/ulwlu/dotfiles/blob/master/system/macos.sh#L1523

Some options doesn't exist at default such as the System Theme. If it's light theme the option doesn't exist at default, but if you switch to the dark theme you can read the option.

**Comment by solzard** [comment]
I finally reached the line you mentioned and then read your reply.
Overall, it's a great reference! I appreciate your dedicated work!🎉
