### ISSUE TITLE
Shortage of an argument in Trackpad > Notification Center?

### ISSUE THREAD

**Issue by solzard** [ulwlu/dotfiles#14]
[`macos.sh`#L1097](https://github.com/ulwlu/dotfiles/blob/00e6dac3549bb3abfaa2f1f9fffd67cb6ea979a2/system/macos.sh#L1097)~L1101 use `defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad -int`.
```sh
  # ========== Notification Center ==========
  # - Checked
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad -int 3
  # - Unchecked
  # defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad -int 0
```

However, I believe this part needs `TrackpadTwoFingerFromRightEdgeSwipeGesture` argument before `-int`.
```
# ========== Notification Center ==========
  # - Checked
  defaults write com.apple.AppleMultitouchTrackpad TrackpadTwoFingerFromRightEdgeSwipeGesture -int 3
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadTwoFingerFromRightEdgeSwipeGesture -int 3
  # - Unchecked
  defaults write com.apple.AppleMultitouchTrackpad TrackpadTwoFingerFromRightEdgeSwipeGesture -int 0
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadTwoFingerFromRightEdgeSwipeGesture -int 0
```

I tried and got the result above in `Mojave 10.14.6` / `MBP13 w/o touch bar (2017)`.

**Comment by ulwlu** [comment]
Oh, really. Thank you very much for good catch.

I'm at work currently, so will check it in about 6 hours.

**Comment by ulwlu** [comment]
@solzard 
Hi, thank you very much for your reporting.
The master branch corrects the code now.
I really appreciate you.
