### ISSUE TITLE
Deprecated brew installer on install.sh

### ISSUE THREAD

**Issue by solzard** [ulwlu/dotfiles#16]
`install.sh#L143` uses ruby to install homebrew, which is deprecated.
https://github.com/ulwlu/dotfiles/blob/8958bf02ba27c6d771b43fb199d826a322bb3f12/install.sh#L143  

[Homebrew](https://brew.sh/) has rewritten the installer in bash and recommends using it.
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by ulwlu** [comment]
@solzard 
Thank you very much, I didn't notice it changed.
The code now fixed. I appreciate you.

Ref:
https://github.com/Homebrew/brew/issues/6256
https://github.com/exercism/interactive-cli-walkthrough/issues/91
