### ISSUE TITLE
Big Sur com.apple.systemuiserver menuExtras error

### ISSUE THREAD

**Issue by dec0dOS** [ulwlu/dotfiles#18]
Hello! Thanks for all your hard work!

menuExtras key does not exist on macOS Big Sur.

```
defaults read com.apple.systemuiserver menuExtras

defaults[15559:64480] 
The domain/default pair of (com.apple.systemuiserver, menuExtras) does not exist
```

So all com.apple.systemuiserver menuExtras related settings doesn't work.

There is some investigations [here](https://www.jamf.com/jamf-nation/discussions/37364/big-sur-bluetooth-menu-no-longer-exists).

**Comment by ulwlu** [comment]
Hi @dec0dOS, thank you for reporting.

I will fix this in 5 days since I'm in busy with my job at this moment.

I also found other domains which are gone after upgrading to bigsur, so trying to fix them as well.

**Comment by ulwlu** [comment]
will be late, sorry.

**Comment by ulwlu** [comment]
As I noticed on https://github.com/ulwlu/dotfiles/issues/23, I will update this when I get motivated.

But it will be a different approach totally. I will dig in MacOS it self, not listing a bunch of commands just like now.

So, anyway, I won't check `defaults` commands and close this issue.
