### ISSUE TITLE
Adapt macos.sh to Big Sur

### ISSUE THREAD

**Issue by ulwlu** [ulwlu/dotfiles#23]

**Comment by ulwlu** [comment]
I think it's time to make some tool.

Check them inside plist, and make it configurable inside json or some format.

**Comment by ulwlu** [comment]
https://qiita.com/tattn/items/0f714344f8c911f5be4c
https://qiita.com/tattn/items/0f714344f8c911f5be4c

or

https://github.com/DHowett/go-plist

rustplist is unstable.

**Comment by ulwlu** [comment]
plsync --read
- specify file : read setting from plist and apply it to json.
- none: read whole and apply it to json

plsync --write
- same as above, but read fron json and apply to plist

Required file are main source and list-file which contains all watching plist keys.

**Comment by dec0dOS** [comment]
I think there is a better way to handle it.
My ansible-based solution becomes clunky, so I'd like to create CLI shell-based general-purpose utility that could configure almost all macOS preferences and then create the wrapper for ansible.
I already have some codebase. Would you like to participate in the development?

**Comment by ulwlu** [comment]
@dec0dOS 
That sounds great. I'm interested in, but not sure if I can contribute much since I'm busy now. If you invite me I'll try my best, though.

Maybe, completing Big Sur commands must be my first mission?
I maybe am going to complete it in this month.

**Comment by dec0dOS** [comment]
Hey, @ulwlu! 

The main design goal is to make the utility as flexible as it can, so it is easy to extend. I've checked out some OSS shell projects. As a result, I've made the plugin subsystem. 
First of all, the output (stdout, stderr, exit codes) of the utility is designed to be used in an automated setup environment. 
Second, all commands need to provide the "read current state" option to make the backup function work. 
Thirdly, the backup config file uses the custom format to make it is easy to use and parse. For now, I don't think there will be many benefits from the adoption of some standard file formats like JSON or YAML/TOML. 

Repo URL: https://github.com/dec0dOS/macos-prefs

When the project reaches the state "just good enough to use", the repo visibility is going to change from "private" to "public".

I'm looking forward to your review! Any suggestions are welcome.

**Comment by ulwlu** [comment]
@dec0dOS 
I see, this must be a good idea. I will add some proposal and ideas into your repo's issue.

Also I gonna complete Big Sur commands anyway. This helps your repo as well. It will be done in this month at least.

**Comment by ulwlu** [comment]
I'll adapt but my main interests are changed. 
How system preferences revokes system software? How to research them? I'll dig in these things maybe rather than trying to maintain the bunch of commands itself.

**Comment by ulwlu** [comment]
So, one day I will work by different approach.

I shall close this at this time.

**Comment by dec0dOS** [comment]
I there really a different approach? Some internal objectiveC/Swift API?

**Comment by ulwlu** [comment]
But your tool is really awesome, I found the code is beautiful and it will definitely help many people. 

I respect that. So if you want some help, please call me anytime.
