### ISSUE TITLE
Some Issues with Dock applications (Path, Syntax Errors, Indexing)

### ISSUE THREAD

**Issue by 5nafu** [ulwlu/dotfiles#24]
Hi @ulwlu,

first of all thank you for your effort with the OSX automation. It is greatly appreciated!

I would like to give something back in hinting at some issues I came across while setting the default (persistent) dock applications:

https://github.com/ulwlu/dotfiles/blob/76867efa663d114955d267e193cd72df5e945589/system/macos.sh#L1414-L1417
At least the AppStore, Mail and SystemPreferences (L1450) are located in the Systems folder (e.g. `file:///System/Applications/Mail.app/`)

https://github.com/ulwlu/dotfiles/blob/76867efa663d114955d267e193cd72df5e945589/system/macos.sh#L1456
`/bin/bash` (v3.2) and the homebrew-`bash` (v5.1) unfortunately complain about a syntax error in the expression. I would suggest to use `DNUM=$(expr ${#dockitem[@]} / 3)` instead.

https://github.com/ulwlu/dotfiles/blob/76867efa663d114955d267e193cd72df5e945589/system/macos.sh#L1457
`HNUM` should be `DNUM` according to the line 1456.

https://github.com/ulwlu/dotfiles/blob/76867efa663d114955d267e193cd72df5e945589/system/macos.sh#L1458-L1460
As a bash array starts with the index `0`, the addition adds one too much and should be `$(( ${idx} * 3 + 0 ))` to `$(( ${idx} * 3 + 2 ))` respectively.

If you prefer, I would be very happy to provide a pull request for the suggested fixes.

Cheers and thank you again,

5nafu

**Comment by ulwlu** [comment]
Hi @5nafu@, it's a great pointing. Thank you very much.

> If you prefer, I would be very happy to provide a pull request for the suggested fixes.

I'm still trying to find the way to fix, so I really appreciate you if you send me PR when you have a time.

**Comment by 5nafu** [comment]
I am happy to present you with #25. I found some other issues with the Spotlight and Finder configuration and added this to the PR. 

I hope this helps.
