### ISSUE TITLE
failed to compile regex: empty (sub)expression

### ISSUE THREAD

**Issue by glaucocustodio** [ulwlu/dotfiles#26]
Hey, thanks for sharing this setup.

I am having the following error `failed to compile regex: empty (sub)expression` on zsh when trying to set default apps, here is my changed snippet (I just changed the editor to Sublime Text basically):

```
LSCT=("public.json" "com.netscape.javascript-source", "public.text")
PLIST="${HOME}/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist"
HNUM=$(/usr/libexec/PlistBuddy -c "Print LSHandlers:" "${PLIST}" | ggrep -cP '^[\s]*Dict')
for idx in $(seq 0 $(expr "${HNUM}" - 1)); do
  THIS_LSCT=$(/usr/libexec/PlistBuddy -c "Print LSHandlers:${idx}:LSHandlerContentType" "${PLIST}" 2> /dev/null)
  if [[ ${LSCT[@]} =~ ${THIS_LSCT} ]]; then
    /usr/libexec/PlistBuddy -c "Set LSHandlers:${idx}:LSHandlerRoleAll com.sublimetext.4" "${PLIST}"
  fi
done
```

the error happens on the following line: `if [[ ${LSCT[@]} =~ ${THIS_LSCT} ]]; then`

Any tips on what could be? Cheers.

**Comment by ulwlu** [comment]
@glaucocustodio 
Hi. It seems working in my env.

<img width="984" alt="ss 3" src="https://user-images.githubusercontent.com/41639488/134984443-7fdb5479-1fc6-4807-88a5-41d8a2e973ce.png">

Can you do `which ggrep` ?
I want to know if that is gnu grep installed by brew.
