### ISSUE TITLE
NewWindowTargetPath instead of NewWindowTarget

### ISSUE THREAD

**Issue by glaucocustodio** [ulwlu/dotfiles#27]
hey the following didn't work for me on big sur:
`defaults write com.apple.finder NewWindowTarget -string "${HOME}/work"`

this one worked:
`defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/work"`

**Comment by ulwlu** [comment]
@glaucocustodio thank you for catching. You are right, I didn't notice that NewWindowTarget got deprecated at Mojave.
